# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_VegeMaker.ui'
#
# Created: Wed Jun 11 10:00:34 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_UI_VegeMaker(object):
    def setupUi(self, UI_VegeMaker):
        UI_VegeMaker.setObjectName(_fromUtf8("UI_VegeMaker"))
        UI_VegeMaker.resize(985, 839)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Images/Arbres.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        UI_VegeMaker.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(UI_VegeMaker)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabINDAT = QtGui.QWidget()
        self.tabINDAT.setObjectName(_fromUtf8("tabINDAT"))
        self.gridLayout = QtGui.QGridLayout(self.tabINDAT)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.btOuvrirPFD = QtGui.QPushButton(self.tabINDAT)
        self.btOuvrirPFD.setObjectName(_fromUtf8("btOuvrirPFD"))
        self.horizontalLayout_6.addWidget(self.btOuvrirPFD)
        self.btFichierIN = QtGui.QPushButton(self.tabINDAT)
        self.btFichierIN.setEnabled(False)
        self.btFichierIN.setObjectName(_fromUtf8("btFichierIN"))
        self.horizontalLayout_6.addWidget(self.btFichierIN)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.btOuvrirIn = QtGui.QPushButton(self.tabINDAT)
        self.btOuvrirIn.setObjectName(_fromUtf8("btOuvrirIn"))
        self.verticalLayout_2.addWidget(self.btOuvrirIn)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.frame = QtGui.QFrame(self.tabINDAT)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_8.addWidget(self.frame)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.btOuvrirXLS = QtGui.QPushButton(self.tabINDAT)
        self.btOuvrirXLS.setObjectName(_fromUtf8("btOuvrirXLS"))
        self.horizontalLayout_7.addWidget(self.btOuvrirXLS)
        self.btFichierDAT = QtGui.QPushButton(self.tabINDAT)
        self.btFichierDAT.setEnabled(False)
        self.btFichierDAT.setObjectName(_fromUtf8("btFichierDAT"))
        self.horizontalLayout_7.addWidget(self.btFichierDAT)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.frame_2 = QtGui.QFrame(self.tabINDAT)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_3.addWidget(self.frame_2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.cbTypePousse = QtGui.QComboBox(self.tabINDAT)
        self.cbTypePousse.setObjectName(_fromUtf8("cbTypePousse"))
        self.gridLayout.addWidget(self.cbTypePousse, 1, 0, 1, 1)
        self.gbPousse = QtGui.QGroupBox(self.tabINDAT)
        self.gbPousse.setEnabled(False)
        self.gbPousse.setObjectName(_fromUtf8("gbPousse"))
        self._2 = QtGui.QGridLayout(self.gbPousse)
        self._2.setMargin(9)
        self._2.setSpacing(6)
        self._2.setObjectName(_fromUtf8("_2"))
        self.txR2SLASL = QtGui.QLineEdit(self.gbPousse)
        self.txR2SLASL.setAlignment(QtCore.Qt.AlignHCenter)
        self.txR2SLASL.setReadOnly(True)
        self.txR2SLASL.setObjectName(_fromUtf8("txR2SLASL"))
        self._2.addWidget(self.txR2SLASL, 3, 2, 1, 1)
        self.btInfoTypePousse = QtGui.QPushButton(self.gbPousse)
        self.btInfoTypePousse.setObjectName(_fromUtf8("btInfoTypePousse"))
        self._2.addWidget(self.btInfoTypePousse, 4, 1, 1, 2)
        self.label_2 = QtGui.QLabel(self.gbPousse)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self._2.addWidget(self.label_2, 2, 0, 1, 1)
        self.txR2NLSL = QtGui.QLineEdit(self.gbPousse)
        self.txR2NLSL.setAlignment(QtCore.Qt.AlignHCenter)
        self.txR2NLSL.setReadOnly(True)
        self.txR2NLSL.setObjectName(_fromUtf8("txR2NLSL"))
        self._2.addWidget(self.txR2NLSL, 3, 1, 1, 1)
        self.txOrigineNLSL = QtGui.QLineEdit(self.gbPousse)
        self.txOrigineNLSL.setAlignment(QtCore.Qt.AlignHCenter)
        self.txOrigineNLSL.setReadOnly(True)
        self.txOrigineNLSL.setObjectName(_fromUtf8("txOrigineNLSL"))
        self._2.addWidget(self.txOrigineNLSL, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gbPousse)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self._2.addWidget(self.label_3, 3, 0, 1, 1)
        self.label = QtGui.QLabel(self.gbPousse)
        self.label.setObjectName(_fromUtf8("label"))
        self._2.addWidget(self.label, 1, 0, 1, 1)
        self._3 = QtGui.QHBoxLayout()
        self._3.setSpacing(6)
        self._3.setMargin(0)
        self._3.setObjectName(_fromUtf8("_3"))
        self.lbNLSL = QtGui.QLabel(self.gbPousse)
        self.lbNLSL.setObjectName(_fromUtf8("lbNLSL"))
        self._3.addWidget(self.lbNLSL)
        self.lbSLASL = QtGui.QLabel(self.gbPousse)
        self.lbSLASL.setObjectName(_fromUtf8("lbSLASL"))
        self._3.addWidget(self.lbSLASL)
        self._2.addLayout(self._3, 0, 1, 1, 2)
        self.txOrigineSLASL = QtGui.QLineEdit(self.gbPousse)
        self.txOrigineSLASL.setAlignment(QtCore.Qt.AlignHCenter)
        self.txOrigineSLASL.setReadOnly(True)
        self.txOrigineSLASL.setObjectName(_fromUtf8("txOrigineSLASL"))
        self._2.addWidget(self.txOrigineSLASL, 2, 2, 1, 1)
        self.txPenteNLSL = QtGui.QLineEdit(self.gbPousse)
        self.txPenteNLSL.setAlignment(QtCore.Qt.AlignHCenter)
        self.txPenteNLSL.setReadOnly(True)
        self.txPenteNLSL.setObjectName(_fromUtf8("txPenteNLSL"))
        self._2.addWidget(self.txPenteNLSL, 1, 1, 1, 1)
        self.txPenteSLASL = QtGui.QLineEdit(self.gbPousse)
        self.txPenteSLASL.setAlignment(QtCore.Qt.AlignHCenter)
        self.txPenteSLASL.setReadOnly(True)
        self.txPenteSLASL.setObjectName(_fromUtf8("txPenteSLASL"))
        self._2.addWidget(self.txPenteSLASL, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.gbPousse, 2, 0, 1, 1)
        self.gbFeuille = QtGui.QGroupBox(self.tabINDAT)
        self.gbFeuille.setEnabled(False)
        self.gbFeuille.setObjectName(_fromUtf8("gbFeuille"))
        self._4 = QtGui.QGridLayout(self.gbFeuille)
        self._4.setMargin(9)
        self._4.setSpacing(6)
        self._4.setObjectName(_fromUtf8("_4"))
        self.btInfoTypeFeuille = QtGui.QPushButton(self.gbFeuille)
        self.btInfoTypeFeuille.setObjectName(_fromUtf8("btInfoTypeFeuille"))
        self._4.addWidget(self.btInfoTypeFeuille, 3, 1, 1, 3)
        self._5 = QtGui.QHBoxLayout()
        self._5.setSpacing(6)
        self._5.setMargin(0)
        self._5.setObjectName(_fromUtf8("_5"))
        self.label_5 = QtGui.QLabel(self.gbFeuille)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self._5.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.gbFeuille)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self._5.addWidget(self.label_6)
        self.label_7 = QtGui.QLabel(self.gbFeuille)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self._5.addWidget(self.label_7)
        self._4.addLayout(self._5, 0, 1, 1, 3)
        self.label_4 = QtGui.QLabel(self.gbFeuille)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self._4.addWidget(self.label_4, 1, 0, 1, 1)
        self.txPenteLALLLW = QtGui.QLineEdit(self.gbFeuille)
        self.txPenteLALLLW.setAlignment(QtCore.Qt.AlignHCenter)
        self.txPenteLALLLW.setReadOnly(True)
        self.txPenteLALLLW.setObjectName(_fromUtf8("txPenteLALLLW"))
        self._4.addWidget(self.txPenteLALLLW, 1, 1, 1, 1)
        self.txPenteLALLLL = QtGui.QLineEdit(self.gbFeuille)
        self.txPenteLALLLL.setAlignment(QtCore.Qt.AlignHCenter)
        self.txPenteLALLLL.setReadOnly(True)
        self.txPenteLALLLL.setObjectName(_fromUtf8("txPenteLALLLL"))
        self._4.addWidget(self.txPenteLALLLL, 1, 2, 1, 1)
        self.txPenteLWLL = QtGui.QLineEdit(self.gbFeuille)
        self.txPenteLWLL.setAlignment(QtCore.Qt.AlignHCenter)
        self.txPenteLWLL.setReadOnly(True)
        self.txPenteLWLL.setObjectName(_fromUtf8("txPenteLWLL"))
        self._4.addWidget(self.txPenteLWLL, 1, 3, 1, 1)
        self.txR2LWLL = QtGui.QLineEdit(self.gbFeuille)
        self.txR2LWLL.setAlignment(QtCore.Qt.AlignHCenter)
        self.txR2LWLL.setReadOnly(True)
        self.txR2LWLL.setObjectName(_fromUtf8("txR2LWLL"))
        self._4.addWidget(self.txR2LWLL, 2, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.gbFeuille)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self._4.addWidget(self.label_8, 2, 0, 1, 1)
        self.txR2LALLLL = QtGui.QLineEdit(self.gbFeuille)
        self.txR2LALLLL.setAlignment(QtCore.Qt.AlignHCenter)
        self.txR2LALLLL.setReadOnly(True)
        self.txR2LALLLL.setObjectName(_fromUtf8("txR2LALLLL"))
        self._4.addWidget(self.txR2LALLLL, 2, 2, 1, 1)
        self.txR2LLALLLW = QtGui.QLineEdit(self.gbFeuille)
        self.txR2LLALLLW.setAlignment(QtCore.Qt.AlignHCenter)
        self.txR2LLALLLW.setReadOnly(True)
        self.txR2LLALLLW.setObjectName(_fromUtf8("txR2LLALLLW"))
        self._4.addWidget(self.txR2LLALLLW, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.gbFeuille, 3, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.txEdit = QtGui.QTextEdit(self.tabINDAT)
        self.txEdit.setObjectName(_fromUtf8("txEdit"))
        self.horizontalLayout_9.addWidget(self.txEdit)
        self.btRAZText = QtGui.QPushButton(self.tabINDAT)
        self.btRAZText.setObjectName(_fromUtf8("btRAZText"))
        self.horizontalLayout_9.addWidget(self.btRAZText)
        self.gridLayout.addLayout(self.horizontalLayout_9, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tabINDAT, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_12.addWidget(self.label_9)
        self.txIN = QtGui.QLineEdit(self.groupBox_5)
        self.txIN.setReadOnly(True)
        self.txIN.setObjectName(_fromUtf8("txIN"))
        self.horizontalLayout_12.addWidget(self.txIN)
        self.btOuvreIN = QtGui.QPushButton(self.groupBox_5)
        self.btOuvreIN.setMaximumSize(QtCore.QSize(20, 16777215))
        self.btOuvreIN.setObjectName(_fromUtf8("btOuvreIN"))
        self.horizontalLayout_12.addWidget(self.btOuvreIN)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_12)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_13.addWidget(self.label_10)
        self.txDAT = QtGui.QLineEdit(self.groupBox_5)
        self.txDAT.setReadOnly(True)
        self.txDAT.setObjectName(_fromUtf8("txDAT"))
        self.horizontalLayout_13.addWidget(self.txDAT)
        self.btOuvreDAT = QtGui.QPushButton(self.groupBox_5)
        self.btOuvreDAT.setMaximumSize(QtCore.QSize(20, 16777215))
        self.btOuvreDAT.setObjectName(_fromUtf8("btOuvreDAT"))
        self.horizontalLayout_13.addWidget(self.btOuvreDAT)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)
        self.gridLayout_7.addLayout(self.horizontalLayout_14, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 0, 0, 1, 2)
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gvPositionFeuille = QtGui.QGraphicsView(self.groupBox_3)
        self.gvPositionFeuille.setInteractive(False)
        self.gvPositionFeuille.setObjectName(_fromUtf8("gvPositionFeuille"))
        self.gridLayout_2.addWidget(self.gvPositionFeuille, 0, 0, 1, 1)
        self.slEcart = QtGui.QSlider(self.groupBox_3)
        self.slEcart.setMinimum(2)
        self.slEcart.setMaximum(10)
        self.slEcart.setPageStep(1)
        self.slEcart.setProperty("value", 2)
        self.slEcart.setOrientation(QtCore.Qt.Horizontal)
        self.slEcart.setTickPosition(QtGui.QSlider.NoTicks)
        self.slEcart.setObjectName(_fromUtf8("slEcart"))
        self.gridLayout_2.addWidget(self.slEcart, 1, 0, 1, 1)
        self.slTaille = QtGui.QSlider(self.groupBox_3)
        self.slTaille.setMinimum(2)
        self.slTaille.setMaximum(10)
        self.slTaille.setPageStep(1)
        self.slTaille.setProperty("value", 2)
        self.slTaille.setOrientation(QtCore.Qt.Horizontal)
        self.slTaille.setTickPosition(QtGui.QSlider.NoTicks)
        self.slTaille.setObjectName(_fromUtf8("slTaille"))
        self.gridLayout_2.addWidget(self.slTaille, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gvPhyllotaxie = QtGui.QGraphicsView(self.groupBox_4)
        self.gvPhyllotaxie.setMinimumSize(QtCore.QSize(0, 300))
        self.gvPhyllotaxie.setMaximumSize(QtCore.QSize(16777215, 400))
        self.gvPhyllotaxie.setObjectName(_fromUtf8("gvPhyllotaxie"))
        self.gridLayout_6.addWidget(self.gvPhyllotaxie, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.lbPhyllotaxie = QtGui.QLabel(self.groupBox_4)
        self.lbPhyllotaxie.setObjectName(_fromUtf8("lbPhyllotaxie"))
        self.horizontalLayout_10.addWidget(self.lbPhyllotaxie)
        self.spinPhyllotaxie = QtGui.QSpinBox(self.groupBox_4)
        self.spinPhyllotaxie.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinPhyllotaxie.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinPhyllotaxie.setMinimum(1)
        self.spinPhyllotaxie.setMaximum(180)
        self.spinPhyllotaxie.setSingleStep(5)
        self.spinPhyllotaxie.setProperty("value", 90)
        self.spinPhyllotaxie.setObjectName(_fromUtf8("spinPhyllotaxie"))
        self.horizontalLayout_10.addWidget(self.spinPhyllotaxie)
        self.gridLayout_6.addLayout(self.horizontalLayout_10, 1, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.gbOpt_2 = QtGui.QGroupBox(self.tab)
        self.gbOpt_2.setObjectName(_fromUtf8("gbOpt_2"))
        self.gridLayout_8 = QtGui.QGridLayout(self.gbOpt_2)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.rbB = QtGui.QRadioButton(self.gbOpt_2)
        self.rbB.setMaximumSize(QtCore.QSize(30, 16777215))
        self.rbB.setObjectName(_fromUtf8("rbB"))
        self.horizontalLayout_18.addWidget(self.rbB)
        self.lbB = QtGui.QLabel(self.gbOpt_2)
        self.lbB.setObjectName(_fromUtf8("lbB"))
        self.horizontalLayout_18.addWidget(self.lbB)
        self.gridLayout_8.addLayout(self.horizontalLayout_18, 1, 0, 1, 1)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.rbD = QtGui.QRadioButton(self.gbOpt_2)
        self.rbD.setMaximumSize(QtCore.QSize(30, 16777215))
        self.rbD.setObjectName(_fromUtf8("rbD"))
        self.horizontalLayout_20.addWidget(self.rbD)
        self.lbD = QtGui.QLabel(self.gbOpt_2)
        self.lbD.setObjectName(_fromUtf8("lbD"))
        self.horizontalLayout_20.addWidget(self.lbD)
        self.gridLayout_8.addLayout(self.horizontalLayout_20, 3, 0, 1, 1)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.rbC = QtGui.QRadioButton(self.gbOpt_2)
        self.rbC.setMaximumSize(QtCore.QSize(30, 16777215))
        self.rbC.setObjectName(_fromUtf8("rbC"))
        self.horizontalLayout_19.addWidget(self.rbC)
        self.lbC = QtGui.QLabel(self.gbOpt_2)
        self.lbC.setObjectName(_fromUtf8("lbC"))
        self.horizontalLayout_19.addWidget(self.lbC)
        self.gridLayout_8.addLayout(self.horizontalLayout_19, 2, 0, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.rbA = QtGui.QRadioButton(self.gbOpt_2)
        self.rbA.setMaximumSize(QtCore.QSize(30, 16777215))
        self.rbA.setChecked(True)
        self.rbA.setObjectName(_fromUtf8("rbA"))
        self.horizontalLayout_16.addWidget(self.rbA)
        self.lbA = QtGui.QLabel(self.gbOpt_2)
        self.lbA.setObjectName(_fromUtf8("lbA"))
        self.horizontalLayout_16.addWidget(self.lbA)
        self.gridLayout_8.addLayout(self.horizontalLayout_16, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.gbOpt_2)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 1, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gbSortie = QtGui.QGroupBox(self.tab)
        self.gbSortie.setObjectName(_fromUtf8("gbSortie"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.gbSortie)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.chFeuilles = QtGui.QCheckBox(self.gbSortie)
        self.chFeuilles.setChecked(True)
        self.chFeuilles.setObjectName(_fromUtf8("chFeuilles"))
        self.horizontalLayout_11.addWidget(self.chFeuilles)
        self.chPetioles = QtGui.QCheckBox(self.gbSortie)
        self.chPetioles.setChecked(False)
        self.chPetioles.setObjectName(_fromUtf8("chPetioles"))
        self.horizontalLayout_11.addWidget(self.chPetioles)
        self.chPousses = QtGui.QCheckBox(self.gbSortie)
        self.chPousses.setChecked(False)
        self.chPousses.setObjectName(_fromUtf8("chPousses"))
        self.horizontalLayout_11.addWidget(self.chPousses)
        self.chFruits = QtGui.QCheckBox(self.gbSortie)
        self.chFruits.setChecked(False)
        self.chFruits.setObjectName(_fromUtf8("chFruits"))
        self.horizontalLayout_11.addWidget(self.chFruits)
        self.horizontalLayout.addWidget(self.gbSortie)
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.rbCm = QtGui.QRadioButton(self.groupBox_2)
        self.rbCm.setObjectName(_fromUtf8("rbCm"))
        self.verticalLayout_4.addWidget(self.rbCm)
        self.rbM = QtGui.QRadioButton(self.groupBox_2)
        self.rbM.setChecked(True)
        self.rbM.setObjectName(_fromUtf8("rbM"))
        self.verticalLayout_4.addWidget(self.rbM)
        self.horizontalLayout.addWidget(self.groupBox_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.btOK_2 = QtGui.QPushButton(self.tab)
        self.btOK_2.setMinimumSize(QtCore.QSize(0, 60))
        self.btOK_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btOK_2.setObjectName(_fromUtf8("btOK_2"))
        self.verticalLayout.addWidget(self.btOK_2)
        self.pgbAllo = QtGui.QProgressBar(self.tab)
        self.pgbAllo.setMaximumSize(QtCore.QSize(500, 16777215))
        self.pgbAllo.setMaximum(10)
        self.pgbAllo.setProperty("value", 0)
        self.pgbAllo.setObjectName(_fromUtf8("pgbAllo"))
        self.verticalLayout.addWidget(self.pgbAllo)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout_4.addLayout(self.horizontalLayout, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget, 0, 1, 1, 1)
        UI_VegeMaker.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(UI_VegeMaker)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 985, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        UI_VegeMaker.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(UI_VegeMaker)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        UI_VegeMaker.setStatusBar(self.statusbar)

        self.retranslateUi(UI_VegeMaker)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(UI_VegeMaker)

    def retranslateUi(self, UI_VegeMaker):
        UI_VegeMaker.setWindowTitle(_translate("UI_VegeMaker", "VegeMaker", None))
        self.btOuvrirPFD.setText(_translate("UI_VegeMaker", "Ouvrir PFD", None))
        self.btFichierIN.setText(_translate("UI_VegeMaker", "-> Fichier IN", None))
        self.btOuvrirIn.setText(_translate("UI_VegeMaker", "Ouvrir IN", None))
        self.btOuvrirXLS.setText(_translate("UI_VegeMaker", "Ouvrir Allometrie", None))
        self.btFichierDAT.setText(_translate("UI_VegeMaker", "-> Fichier DAT", None))
        self.gbPousse.setTitle(_translate("UI_VegeMaker", "Pousses", None))
        self.btInfoTypePousse.setText(_translate("UI_VegeMaker", "Enregistrer donnees", None))
        self.label_2.setText(_translate("UI_VegeMaker", "origine", None))
        self.label_3.setText(_translate("UI_VegeMaker", "R²", None))
        self.label.setText(_translate("UI_VegeMaker", "pente", None))
        self.lbNLSL.setText(_translate("UI_VegeMaker", "NL=f(SL)", None))
        self.lbSLASL.setText(_translate("UI_VegeMaker", "SLA = f(SL)", None))
        self.gbFeuille.setTitle(_translate("UI_VegeMaker", "Feuilles", None))
        self.btInfoTypeFeuille.setText(_translate("UI_VegeMaker", "Enregistrer donnees", None))
        self.label_5.setText(_translate("UI_VegeMaker", "LA =f(LL*LW)", None))
        self.label_6.setText(_translate("UI_VegeMaker", "LA =f(LL*LL)", None))
        self.label_7.setText(_translate("UI_VegeMaker", "LW =f(LL)", None))
        self.label_4.setText(_translate("UI_VegeMaker", "pente", None))
        self.label_8.setText(_translate("UI_VegeMaker", "R²", None))
        self.btRAZText.setText(_translate("UI_VegeMaker", "Clear", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabINDAT), _translate("UI_VegeMaker", "Fichiers IN et DAT", None))
        self.groupBox_5.setTitle(_translate("UI_VegeMaker", "Fichiers d\'entree", None))
        self.label_9.setText(_translate("UI_VegeMaker", "Fichier IN", None))
        self.btOuvreIN.setText(_translate("UI_VegeMaker", "...", None))
        self.label_10.setText(_translate("UI_VegeMaker", "Fichier DAT", None))
        self.btOuvreDAT.setText(_translate("UI_VegeMaker", "...", None))
        self.groupBox_3.setTitle(_translate("UI_VegeMaker", "Position et taille des feuilles", None))
        self.groupBox_4.setTitle(_translate("UI_VegeMaker", "Phyllotaxie", None))
        self.lbPhyllotaxie.setText(_translate("UI_VegeMaker", "Angle de phylotaxie", None))
        self.gbOpt_2.setTitle(_translate("UI_VegeMaker", "Options de sortie", None))
        self.rbB.setText(_translate("UI_VegeMaker", "B", None))
        self.lbB.setText(_translate("UI_VegeMaker", "Une couleur par entite, le reste en noir", None))
        self.rbD.setText(_translate("UI_VegeMaker", "D", None))
        self.lbD.setText(_translate("UI_VegeMaker", "Sortie feuilles vertes fruit rouges ", None))
        self.rbC.setText(_translate("UI_VegeMaker", "C", None))
        self.lbC.setText(_translate("UI_VegeMaker", "Une couleur par fruit, le reste en noir", None))
        self.rbA.setText(_translate("UI_VegeMaker", "A", None))
        self.lbA.setText(_translate("UI_VegeMaker", "Tout en noir", None))
        self.gbSortie.setTitle(_translate("UI_VegeMaker", "Sortir fichier Vgx", None))
        self.chFeuilles.setText(_translate("UI_VegeMaker", "Feuilles", None))
        self.chPetioles.setText(_translate("UI_VegeMaker", "Petioles", None))
        self.chPousses.setText(_translate("UI_VegeMaker", "Pousses", None))
        self.chFruits.setText(_translate("UI_VegeMaker", "Fruits", None))
        self.groupBox_2.setTitle(_translate("UI_VegeMaker", "Unites", None))
        self.rbCm.setText(_translate("UI_VegeMaker", "cm (Digit)", None))
        self.rbM.setText(_translate("UI_VegeMaker", "m (LiDar)", None))
        self.btOK_2.setText(_translate("UI_VegeMaker", "OK", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("UI_VegeMaker", "Generation maquette", None))

